create table if not exists public.users (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null,
  senha text not null,
  nivel_acesso text not null default 'vendedor',
  telefone text,
  comissao numeric(12,2) not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists users_email_unique on public.users (lower(email));

create table if not exists public.vendedores (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null,
  telefone text,
  nivel_acesso text not null default 'vendedor',
  comissao numeric(12,2) not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vendedores_email_unique on public.vendedores (lower(email));

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  vendedor_id bigint references public.vendedores(id) on delete set null,
  cnpj text,
  razao_social text not null,
  nome_fantasia text not null,
  email text,
  telefone text,
  endereco text,
  cidade text,
  estado text,
  cep text,
  inscricao_estadual text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists clientes_cnpj_unique
  on public.clientes (cnpj)
  where cnpj is not null and cnpj <> '';

create index if not exists clientes_vendedor_id_idx on public.clientes (vendedor_id);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  codigo text,
  nome text not null,
  descricao text,
  preco_tabela numeric(12,2) not null default 0,
  preco_custo numeric(12,2) not null default 0,
  estoque_atual numeric(12,2) not null default 0,
  estoque_minimo numeric(12,2) not null default 0,
  unidade_medida text not null default 'UN',
  ativo boolean not null default true,
  imagem_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists produtos_codigo_unique
  on public.produtos (codigo)
  where codigo is not null and codigo <> '';

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero_pedido text not null,
  cliente_id bigint references public.clientes(id) on delete set null,
  vendedor_id bigint references public.vendedores(id) on delete set null,
  data_emissao timestamptz,
  valor_total numeric(12,2) not null default 0,
  condicao_pagamento text,
  observacoes text,
  status text not null default 'pendente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pedidos_cliente_id_idx on public.pedidos (cliente_id);
create index if not exists pedidos_vendedor_id_idx on public.pedidos (vendedor_id);

create table if not exists public.pedido_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id bigint references public.produtos(id) on delete set null,
  quantidade numeric(12,2) not null default 0,
  preco_unitario numeric(12,2) not null default 0,
  desconto numeric(5,2) not null default 0,
  subtotal numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists pedido_itens_pedido_id_idx on public.pedido_itens (pedido_id);
create index if not exists pedido_itens_produto_id_idx on public.pedido_itens (produto_id);

grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
